//> using publish.ci.repository "central"
//> using publish.ci.computeVersion "git:tag"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/alexarchambault/case-app-entrypoint-annotation"
//> using publish.versionControl "github:alexarchambault/case-app-entrypoint-annotation"
//> using publish.developer "Alex Archambault||https://github.com/alexarchambault"
