name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: VirtusLab/scala-cli-setup@v0.1
    - name: Compile
      run: ./mill -i __.compile

  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: VirtusLab/scala-cli-setup@v0.1
    - name: Publish
      run: ./mill -i io.kipp.mill.ci.release.ReleaseModule/publishAll
      env:
        SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
        SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
        PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
